'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'te' | 'hi' | 'ta' | 'kn' | 'mr' | 'bn' | 'bho';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// ─── TRANSLATIONS ───────────────────────────────────────────────────────────
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav & Dashboard
    dashboard: 'Dashboard',
    askAIDoctor: 'Ask AI Doctor',
    symptomChecker: 'Symptom Checker',
    medicineFinder: 'Medicine Finder',
    medicineScanner: 'Medicine Scanner',
    medicalReports: 'Medical Reports',
    healthTracker: 'Health Tracker',
    appointments: 'Appointments',
    emergency: 'Emergency',
    hospitals: 'Hospitals',
    settings: 'Settings',
    searchPlaceholder: 'Ask about symptoms, medicines, diseases...',
    onlineDoctor: 'Online Doctor',
    nearbyHospitals: 'Nearby Hospitals',
    viewAll: 'View All',
    selectLocation: 'Select Location',
    medicineInfo: 'Medicine Info',
    scanMedicine: 'Scan Medicine',
    scanDescription: 'Scan any medicine to get complete details instantly',
    aiDiagnosis: 'AI Diagnosis Suggestion',
    healthStats: 'Health Stats',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    sugarLevel: 'Sugar Level',
    enterSymptoms: 'Enter your symptoms below',
    aiSuggestion: 'AI Suggestion',
    possibleViral: 'Possible Viral Infection',
    condition: 'Possible Condition',
    openFull: 'Open Full Checker',
    usedFor: 'Used for',
    dosage: 'Dosage',
    availability: 'Availability',
    healthPredictors: 'Health Predictors',

    // Medical Profile
    medicalProfile: 'Medical Profile',
    myMedicalProfile: 'My Medical Profile',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    age: 'Age',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    medicalConditions: 'Medical Conditions',
    currentMedications: 'Current Medications',
    allergies: 'Allergies',
    vitals: 'Vitals',
    emergencyContact: 'Emergency Contact',
    preferredHospitals: 'Preferred Hospitals',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile Saved!',
    saving: 'Saving…',
    privateData: 'Private — only visible to you',
    profileAutoFills: 'Profile saved — auto-fills your SOS alerts',
    completeProfile: 'Complete your Medical Profile',
    organDonor: 'I am an Organ Donor',
    doctorNotes: 'Special Notes for Doctors',
    insurance: 'Insurance',
    hasInsurance: 'I have health insurance',
    policyNumber: 'Policy Number',

    // Settings
    profilePicture: 'Profile Picture',
    uploadPhoto: 'Upload Photo',
    displayName: 'Display Name',
    email: 'Email',
    bio: 'Bio',
    saveChanges: 'Save Changes',
    appearance: 'Appearance',
    lightMode: 'Light',
    darkMode: 'Dark',
    systemMode: 'System',
    notifications: 'Notifications',
    privacy: 'Privacy',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account & Data',

    // SOS / Crisis
    emergency_title: 'Emergency?',
    emergency_subtitle: 'Instant help is one tap away. Press the button to alert hotel staff immediately.',
    reportEmergency: 'Report Emergency',
    yourName: 'Your Name',
    roomNo: 'Room No.',
    floor: 'Floor',
    emergencyType: 'Emergency Type',
    describeEmergency: 'Describe the Emergency',
    sendAlert: 'Send Emergency Alert',
    alertCreated: 'Alert Created',
    helpDispatched: 'Help is being dispatched',
    medicalProfileLoaded: 'Medical Profile Auto-Loaded',
    noProfileFound: 'No medical profile found.',
    setOneUp: 'Set one up',
    fasterCare: 'for faster emergency care.',
    profileSentToHospital: 'This data will be sent to hotel staff and the hospital automatically.',

    // Hospital Portal
    hospitalPortal: 'Hospital Emergency Portal',
    incomingPatients: 'Incoming Patients',
    acknowledgeAlert: 'Acknowledge Alert',
    bedReady: 'Bed Ready',
    patientArrived: 'Patient Arrived',
    assignBed: 'Assign Bed',
    assignResponder: 'Assign Responder',
    noIncomingAlerts: 'No incoming patient alerts',
    icdCode: 'ICD-10 Code',
    condition_label: 'Condition',
    department: 'Department',
    bloodType: 'Blood Type',
    knownConditions: 'Known Conditions',
    medications: 'Medications',
    preferredHospital: 'Preferred Hospital',

    // Auth
    welcomeBack: 'Welcome Back',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    continueWithGoogle: 'Continue with Google',
    or: 'or',

    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    refresh: 'Refresh',
    connected: 'Connected',
    connecting: 'Connecting...',
    error: 'Error',
    success: 'Success',
  },

  hi: {
    dashboard: 'डैशबोर्ड',
    askAIDoctor: 'AI डॉक्टर से पूछें',
    symptomChecker: 'लक्षण जाँचक',
    medicineFinder: 'दवा खोजक',
    medicineScanner: 'दवा स्कैनर',
    medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर',
    appointments: 'अपॉइंटमेंट',
    emergency: 'आपातकालीन',
    hospitals: 'अस्पताल',
    settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षणों, दवाओं, रोगों के बारे में पूछें...',
    onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'पास के अस्पताल',
    viewAll: 'सभी देखें',
    selectLocation: 'स्थान चुनें',
    medicineInfo: 'दवा की जानकारी',
    scanMedicine: 'दवा स्कैन करें',
    scanDescription: 'किसी भी दवा को तुरंत स्कैन करें और विवरण प्राप्त करें',
    aiDiagnosis: 'AI निदान सुझाव',
    healthStats: 'स्वास्थ्य आँकड़े',
    heartRate: 'हृदय गति',
    bloodPressure: 'रक्तचाप',
    sugarLevel: 'शुगर लेवल',
    enterSymptoms: 'नीचे अपने लक्षण दर्ज करें',
    aiSuggestion: 'AI सुझाव',
    possibleViral: 'संभावित वायरल संक्रमण',
    condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलें',
    usedFor: 'के लिए उपयोग किया जाता है',
    dosage: 'खुराक',
    availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
    medicalProfile: 'मेडिकल प्रोफ़ाइल',
    myMedicalProfile: 'मेरी मेडिकल प्रोफ़ाइल',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    age: 'आयु',
    dateOfBirth: 'जन्म तिथि',
    gender: 'लिंग',
    bloodGroup: 'रक्त समूह',
    height: 'ऊँचाई (सेमी)',
    weight: 'वज़न (किग्रा)',
    medicalConditions: 'चिकित्सा स्थितियाँ',
    currentMedications: 'वर्तमान दवाएँ',
    allergies: 'एलर्जी',
    vitals: 'महत्वपूर्ण संकेत',
    emergencyContact: 'आपातकालीन संपर्क',
    preferredHospitals: 'पसंदीदा अस्पताल',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    profileSaved: 'प्रोफ़ाइल सहेजी गई!',
    saving: 'सहेजा जा रहा है…',
    privateData: 'निजी — केवल आपको दिखता है',
    profileAutoFills: 'प्रोफ़ाइल सहेजी — SOS अलर्ट में स्वतः भरती है',
    completeProfile: 'अपनी मेडिकल प्रोफ़ाइल पूरी करें',
    organDonor: 'मैं अंग दाता हूँ',
    doctorNotes: 'डॉक्टरों के लिए विशेष नोट्स',
    insurance: 'बीमा',
    hasInsurance: 'मेरे पास स्वास्थ्य बीमा है',
    policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफ़ाइल तस्वीर',
    uploadPhoto: 'तस्वीर अपलोड करें',
    displayName: 'प्रदर्शन नाम',
    email: 'ईमेल',
    bio: 'परिचय',
    saveChanges: 'परिवर्तन सहेजें',
    appearance: 'दिखावट',
    lightMode: 'लाइट',
    darkMode: 'डार्क',
    systemMode: 'सिस्टम',
    notifications: 'सूचनाएँ',
    privacy: 'गोपनीयता',
    signOut: 'साइन आउट',
    deleteAccount: 'खाता और डेटा हटाएँ',
    emergency_title: 'आपातकाल?',
    emergency_subtitle: 'तत्काल सहायता एक टैप दूर है। होटल स्टाफ को तुरंत सतर्क करने के लिए बटन दबाएँ।',
    reportEmergency: 'आपातकाल की रिपोर्ट करें',
    yourName: 'आपका नाम',
    roomNo: 'कमरा नंबर',
    floor: 'मंज़िल',
    emergencyType: 'आपातकाल का प्रकार',
    describeEmergency: 'आपातकाल का वर्णन करें',
    sendAlert: 'आपातकाल अलर्ट भेजें',
    alertCreated: 'अलर्ट बना दिया गया',
    helpDispatched: 'सहायता भेजी जा रही है',
    medicalProfileLoaded: 'मेडिकल प्रोफ़ाइल स्वतः लोड हुई',
    noProfileFound: 'कोई मेडिकल प्रोफ़ाइल नहीं मिली।',
    setOneUp: 'अभी बनाएँ',
    fasterCare: 'तेज़ आपातकालीन देखभाल के लिए।',
    profileSentToHospital: 'यह डेटा होटल स्टाफ और अस्पताल को स्वचालित रूप से भेजा जाएगा।',
    hospitalPortal: 'अस्पताल आपातकाल पोर्टल',
    incomingPatients: 'आने वाले मरीज़',
    acknowledgeAlert: 'अलर्ट स्वीकार करें',
    bedReady: 'बिस्तर तैयार',
    patientArrived: 'मरीज़ पहुँच गया',
    assignBed: 'बिस्तर आवंटित करें',
    assignResponder: 'रेस्पॉंडर नियुक्त करें',
    noIncomingAlerts: 'कोई आने वाले मरीज़ अलर्ट नहीं',
    icdCode: 'ICD-10 कोड',
    condition_label: 'स्थिति',
    department: 'विभाग',
    bloodType: 'रक्त प्रकार',
    knownConditions: 'ज्ञात स्थितियाँ',
    medications: 'दवाएँ',
    preferredHospital: 'पसंदीदा अस्पताल',
    welcomeBack: 'वापसी पर स्वागत है',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    continueWithGoogle: 'Google से जारी रखें',
    or: 'या',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'अगला',
    submit: 'सबमिट करें',
    refresh: 'रिफ्रेश करें',
    connected: 'कनेक्टेड',
    connecting: 'कनेक्ट हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
  },

  te: {
    dashboard: 'డాష్‌బోర్డ్',
    askAIDoctor: 'AI డాక్టర్‌ని అడగండి',
    symptomChecker: 'లక్షణాల తనిఖీ',
    medicineFinder: 'మందుల అన్వేషణ',
    medicineScanner: 'మందుల స్కానర్',
    medicalReports: 'వైద్య నివేదికలు',
    healthTracker: 'ఆరోగ్య ట్రాకర్',
    appointments: 'అపాయింట్‌మెంట్‌లు',
    emergency: 'అత్యవసర',
    hospitals: 'ఆసుపత్రులు',
    settings: 'సెట్టింగ్‌లు',
    searchPlaceholder: 'లక్షణాలు, మందులు, వ్యాధుల గురించి అడగండి...',
    onlineDoctor: 'ఆన్‌లైన్ డాక్టర్',
    nearbyHospitals: 'సమీప ఆసుపత్రులు',
    viewAll: 'అన్నీ చూడు',
    selectLocation: 'స్థానాన్ని ఎంచుకోండి',
    medicineInfo: 'మందుల సమాచారం',
    scanMedicine: 'మెడిసిన్ స్కాన్ చేయండి',
    scanDescription: 'ఏదైనా మందుని తక్షణమే స్కాన్ చేసి వివరాలు పొందండి',
    aiDiagnosis: 'AI రోగనిర్ధారణ సూచన',
    healthStats: 'ఆరోగ్య గణాంకాలు',
    heartRate: 'గుండె వేగం',
    bloodPressure: 'రక్తపోటు',
    sugarLevel: 'షుగర్ లెవల్',
    enterSymptoms: 'మీ లక్షణాలను క్రింద నమోదు చేయండి',
    aiSuggestion: 'AI సూచన',
    possibleViral: 'వైరల్ ఇన్ఫెక్షన్ కావచ్చు',
    condition: 'సాధ్యమైన పరిస్థితి',
    openFull: 'పూర్తి తనిఖీని తెరవండి',
    usedFor: 'కోసం ఉపయోగించబడుతుంది',
    dosage: 'మోతాదు',
    availability: 'అందుబాటులో ఉంది',
    healthPredictors: 'ఆరోగ్య అంచనాలు',
    medicalProfile: 'వైద్య ప్రొఫైల్',
    myMedicalProfile: 'నా వైద్య ప్రొఫైల్',
    personalInfo: 'వ్యక్తిగత సమాచారం',
    fullName: 'పూర్తి పేరు',
    age: 'వయసు',
    dateOfBirth: 'పుట్టిన తేదీ',
    gender: 'లింగం',
    bloodGroup: 'రక్త సమూహం',
    height: 'ఎత్తు (సెమీ)',
    weight: 'బరువు (కేజీ)',
    medicalConditions: 'వైద్య పరిస్థితులు',
    currentMedications: 'ప్రస్తుత మందులు',
    allergies: 'అలెర్జీలు',
    vitals: 'జీవ సంకేతాలు',
    emergencyContact: 'అత్యవసర సంప్రదింపు',
    preferredHospitals: 'ఇష్టమైన ఆసుపత్రులు',
    saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
    profileSaved: 'ప్రొఫైల్ సేవ్ అయింది!',
    saving: 'సేవ్ అవుతోంది…',
    privateData: 'ప్రైవేట్ — మీకు మాత్రమే కనిపిస్తుంది',
    profileAutoFills: 'ప్రొఫైల్ సేవ్ అయింది — SOS అప్రమత్తాలలో స్వయంచాలిత నింపడం',
    completeProfile: 'మీ వైద్య ప్రొఫైల్‌ను పూర్తి చేయండి',
    organDonor: 'నేను అవయవ దాత',
    doctorNotes: 'వైద్యులకు ప్రత్యేక గమనికలు',
    insurance: 'బీమా',
    hasInsurance: 'నాకు ఆరోగ్య బీమా ఉంది',
    policyNumber: 'పాలసీ నంబర్',
    profilePicture: 'ప్రొఫైల్ చిత్రం',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
    displayName: 'ప్రదర్శన పేరు',
    email: 'ఇమెయిల్',
    bio: 'పరిచయం',
    saveChanges: 'మార్పులు సేవ్ చేయండి',
    appearance: 'రూపం',
    lightMode: 'లైట్',
    darkMode: 'డార్క్',
    systemMode: 'సిస్టమ్',
    notifications: 'నోటిఫికేషన్లు',
    privacy: 'గోప్యత',
    signOut: 'సైన్ అవుట్',
    deleteAccount: 'ఖాతా మరియు డేటా తొలగించండి',
    emergency_title: 'అత్యవసరం?',
    emergency_subtitle: 'తక్షణ సహాయం ఒక్క నొక్కు దూరంలో ఉంది. హోటల్ సిబ్బందిని వెంటనే హెచ్చరించడానికి బటన్ నొక్కండి.',
    reportEmergency: 'అత్యవసరం నివేదించండి',
    yourName: 'మీ పేరు',
    roomNo: 'గది నంబర్',
    floor: 'అంతస్తు',
    emergencyType: 'అత్యవసర రకం',
    describeEmergency: 'అత్యవసరాన్ని వివరించండి',
    sendAlert: 'అత్యవసర హెచ్చరిక పంపండి',
    alertCreated: 'హెచ్చరిక సృష్టించబడింది',
    helpDispatched: 'సహాయం పంపబడుతోంది',
    medicalProfileLoaded: 'వైద్య ప్రొఫైల్ స్వయంచాలితంగా లోడ్ అయింది',
    noProfileFound: 'వైద్య ప్రొఫైల్ కనుగొనబడలేదు.',
    setOneUp: 'ఒకటి సెటప్ చేయండి',
    fasterCare: 'వేగవంతమైన అత్యవసర సంరక్షణ కోసం.',
    profileSentToHospital: 'ఈ డేటా హోటల్ సిబ్బంది మరియు ఆసుపత్రికి స్వయంచాలితంగా పంపబడుతుంది.',
    hospitalPortal: 'ఆసుపత్రి అత్యవసర పోర్టల్',
    incomingPatients: 'వచ్చే రోగులు',
    acknowledgeAlert: 'హెచ్చరికను ధృవీకరించండి',
    bedReady: 'మంచం సిద్ధంగా ఉంది',
    patientArrived: 'రోగి వచ్చాడు',
    assignBed: 'మంచం కేటాయించండి',
    assignResponder: 'రెస్పాండర్‌ను నియమించండి',
    noIncomingAlerts: 'ఇన్‌కమింగ్ పేషెంట్ అలర్ట్‌లు లేవు',
    icdCode: 'ICD-10 కోడ్',
    condition_label: 'పరిస్థితి',
    department: 'విభాగం',
    bloodType: 'రక్త రకం',
    knownConditions: 'తెలిసిన పరిస్థితులు',
    medications: 'మందులు',
    preferredHospital: 'ఇష్టమైన ఆసుపత్రి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    continueWithGoogle: 'Google తో కొనసాగించు',
    or: 'లేదా',
    loading: 'లోడ్ అవుతోంది...',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    close: 'మూసివేయండి',
    back: 'వెనుకకు',
    next: 'తదుపరి',
    submit: 'సబ్మిట్ చేయండి',
    refresh: 'రిఫ్రెష్ చేయండి',
    connected: 'కనెక్ట్ అయింది',
    connecting: 'కనెక్ట్ అవుతోంది...',
    error: 'లోపం',
    success: 'విజయం',
  },

  ta: {
    dashboard: 'டாஷ்போர்டு',
    askAIDoctor: 'AI மருத்துவரிடம் கேளுங்கள்',
    symptomChecker: 'அறிகுறி சரிபார்ப்பு',
    medicineFinder: 'மருந்து தேடல்',
    medicineScanner: 'மருந்து ஸ்கேனர்',
    medicalReports: 'மருத்துவ அறிக்கைகள்',
    healthTracker: 'சுகாதார டிராக்கர்',
    appointments: 'நியமனங்கள்',
    emergency: 'அவசரம்',
    hospitals: 'மருத்துவமனைகள்',
    settings: 'அமைப்புகள்',
    searchPlaceholder: 'அறிகுறிகள், மருந்துகள், நோய்கள் பற்றி கேளுங்கள்...',
    onlineDoctor: 'ஆன்லைன் மருத்துவர்',
    nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    viewAll: 'அனைத்தையும் பார்',
    selectLocation: 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    medicineInfo: 'மருந்து தகவல்',
    scanMedicine: 'மருந்தை ஸ்கேன் செய்யுங்கள்',
    scanDescription: 'எந்த மருந்தையும் உடனடியாக ஸ்கேன் செய்து விவரங்களைப் பெறுங்கள்',
    aiDiagnosis: 'AI நோயறிதல் பரிந்துரை',
    healthStats: 'சுகாதார புள்ளிவிவரங்கள்',
    heartRate: 'இதய துடிப்பு',
    bloodPressure: 'இரத்த அழுத்தம்',
    sugarLevel: 'சர்க்கரை அளவு',
    enterSymptoms: 'உங்கள் அறிகுறிகளை கீழே உள்ளிடவும்',
    aiSuggestion: 'AI பரிந்துரை',
    possibleViral: 'வைரஸ் தொற்று இருக்கலாம்',
    condition: 'சாத்தியமான நிலை',
    openFull: 'முழு சரிபார்ப்பைத் திற',
    usedFor: 'பயன்படுத்தப்படுகிறது',
    dosage: 'அளவு',
    availability: 'கிடைக்கும் தன்மை',
    healthPredictors: 'சுகாதார முன்கணிப்பாளர்கள்',
    medicalProfile: 'மருத்துவ சுயவிவரம்',
    myMedicalProfile: 'என் மருத்துவ சுயவிவரம்',
    personalInfo: 'தனிப்பட்ட தகவல்',
    fullName: 'முழு பெயர்',
    age: 'வயது',
    dateOfBirth: 'பிறந்த தேதி',
    gender: 'பாலினம்',
    bloodGroup: 'இரத்த வகை',
    height: 'உயரம் (செமீ)',
    weight: 'எடை (கிகி)',
    medicalConditions: 'மருத்துவ நிலைகள்',
    currentMedications: 'தற்போதைய மருந்துகள்',
    allergies: 'ஒவ்வாமைகள்',
    vitals: 'உயிர் அறிகுறிகள்',
    emergencyContact: 'அவசர தொடர்பு',
    preferredHospitals: 'விரும்பிய மருத்துவமனைகள்',
    saveProfile: 'சுயவிவரத்தை சேமி',
    profileSaved: 'சுயவிவரம் சேமிக்கப்பட்டது!',
    saving: 'சேமிக்கிறது…',
    privateData: 'தனிப்பட்டது — உங்களுக்கு மட்டுமே தெரியும்',
    profileAutoFills: 'சுயவிவரம் சேமிக்கப்பட்டது — SOS எச்சரிக்கைகளில் தானாக நிரப்பும்',
    completeProfile: 'உங்கள் மருத்துவ சுயவிவரத்தை நிரப்புங்கள்',
    organDonor: 'நான் உறுப்பு தானம் செய்பவர்',
    doctorNotes: 'மருத்துவர்களுக்கான சிறப்பு குறிப்புகள்',
    insurance: 'காப்பீடு',
    hasInsurance: 'என்னிடம் சுகாதார காப்பீடு உள்ளது',
    policyNumber: 'பாலிசி எண்',
    profilePicture: 'சுயவிவர படம்',
    uploadPhoto: 'புகைப்படம் பதிவேற்றவும்',
    displayName: 'காட்சி பெயர்',
    email: 'மின்னஞ்சல்',
    bio: 'சுயவிவரம்',
    saveChanges: 'மாற்றங்களை சேமி',
    appearance: 'தோற்றம்',
    lightMode: 'வெளிச்சம்',
    darkMode: 'இருட்டு',
    systemMode: 'கணினி',
    notifications: 'அறிவிப்புகள்',
    privacy: 'தனியுரிமை',
    signOut: 'வெளியேறு',
    deleteAccount: 'கணக்கு மற்றும் தரவை நீக்கு',
    emergency_title: 'அவசரம்?',
    emergency_subtitle: 'உடனடி உதவி ஒரு தட்டு தூரத்தில் உள்ளது. ஹோட்டல் ஊழியர்களுக்கு உடனடியாக எச்சரிக்கை விடுக்க பொத்தானை அழுத்தவும்.',
    reportEmergency: 'அவசரநிலையை புகாரளிக்கவும்',
    yourName: 'உங்கள் பெயர்',
    roomNo: 'அறை எண்',
    floor: 'தளம்',
    emergencyType: 'அவசரநிலை வகை',
    describeEmergency: 'அவசரநிலையை விவரிக்கவும்',
    sendAlert: 'அவசர எச்சரிக்கை அனுப்பு',
    alertCreated: 'எச்சரிக்கை உருவாக்கப்பட்டது',
    helpDispatched: 'உதவி அனுப்பப்படுகிறது',
    medicalProfileLoaded: 'மருத்துவ சுயவிவரம் தானாக ஏற்றப்பட்டது',
    noProfileFound: 'மருத்துவ சுயவிவரம் காணவில்லை.',
    setOneUp: 'ஒன்றை அமைக்கவும்',
    fasterCare: 'விரைவான அவசர சிகிச்சைக்கு.',
    profileSentToHospital: 'இந்த தரவு ஹோட்டல் ஊழியர்கள் மற்றும் மருத்துவமனைக்கு தானாக அனுப்பப்படும்.',
    hospitalPortal: 'மருத்துவமனை அவசர போர்டல்',
    incomingPatients: 'வரும் நோயாளிகள்',
    acknowledgeAlert: 'எச்சரிக்கையை ஏற்கவும்',
    bedReady: 'படுக்கை தயார்',
    patientArrived: 'நோயாளி வந்தார்',
    assignBed: 'படுக்கை ஒதுக்கவும்',
    assignResponder: 'பதிலாளரை நியமிக்கவும்',
    noIncomingAlerts: 'உள்வரும் நோயாளி எச்சரிக்கைகள் இல்லை',
    icdCode: 'ICD-10 குறியீடு',
    condition_label: 'நிலை',
    department: 'துறை',
    bloodType: 'இரத்த வகை',
    knownConditions: 'அறியப்பட்ட நிலைகள்',
    medications: 'மருந்துகள்',
    preferredHospital: 'விரும்பிய மருத்துவமனை',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signIn: 'உள்நுழைவு',
    signUp: 'பதிவு செய்யவும்',
    continueWithGoogle: 'Google உடன் தொடரவும்',
    or: 'அல்லது',
    loading: 'ஏற்றுகிறது...',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
    back: 'திரும்பு',
    next: 'அடுத்து',
    submit: 'சமர்ப்பி',
    refresh: 'புதுப்பி',
    connected: 'இணைக்கப்பட்டது',
    connecting: 'இணைக்கிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
  },

  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', askAIDoctor: 'AI ವೈದ್ಯರನ್ನು ಕೇಳಿ', symptomChecker: 'ಲಕ್ಷಣಗಳ ತಪಾಸಣೆ',
    medicineFinder: 'ಔಷಧ ಶೋಧಕ', medicineScanner: 'ಔಷಧ ಸ್ಕ್ಯಾನರ್', medicalReports: 'ವೈದ್ಯಕೀಯ ವರದಿಗಳು',
    healthTracker: 'ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್', appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು', emergency: 'ತುರ್ತು',
    hospitals: 'ಆಸ್ಪತ್ರೆಗಳು', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    searchPlaceholder: 'ಲಕ್ಷಣಗಳು, ಔಷಧಗಳು, ಕಾಯಿಲೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...', onlineDoctor: 'ಆನ್‌ಲೈನ್ ವೈದ್ಯರು',
    nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ', selectLocation: 'ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    medicineInfo: 'ಔಷಧ ಮಾಹಿತಿ', scanMedicine: 'ಔಷಧ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanDescription: 'ತಕ್ಷಣದ ವಿವರಗಳನ್ನು ಪಡೆಯಲು ಯಾವುದೇ ಔಷಧವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    aiDiagnosis: 'AI ರೋಗನಿರ್ಣಯ ಸಲಹೆ', healthStats: 'ಆರೋಗ್ಯ ಅಂಕಿಅಂಶಗಳು', heartRate: 'ಹೃದಯ ಬಡಿತ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ', sugarLevel: 'ಸಕ್ಕರೆ ಮಟ್ಟ', enterSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಕೆಳಗೆ ನಮೂದಿಸಿ',
    aiSuggestion: 'AI ಸಲಹೆ', possibleViral: 'ವೈರಲ್ ಸೋಂಕು ಇರಬಹುದು', condition: 'ಸಂಭವನೀಯ ಸ್ಥಿತಿ',
    openFull: 'ಪೂರ್ಣ ತಪಾಸಣೆ ತೆರೆಯಿರಿ', usedFor: 'ಬಳಸಲಾಗುತ್ತದೆ', dosage: 'ಡೋಸೇಜ್', availability: 'ಲಭ್ಯತೆ',
    healthPredictors: 'ಆರೋಗ್ಯ ಮುನ್ಸೂಚಕಗಳು',
    medicalProfile: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್', myMedicalProfile: 'ನನ್ನ ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್',
    personalInfo: 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', age: 'ವಯಸ್ಸು', dateOfBirth: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    gender: 'ಲಿಂಗ', bloodGroup: 'ರಕ್ತ ಗುಂಪು', height: 'ಎತ್ತರ (ಸೆಮಿ)', weight: 'ತೂಕ (ಕಿಗ್ರಾ)',
    medicalConditions: 'ವೈದ್ಯಕೀಯ ಸ್ಥಿತಿಗಳು', currentMedications: 'ಪ್ರಸ್ತುತ ಔಷಧಗಳು', allergies: 'ಅಲರ್ಜಿಗಳು',
    vitals: 'ಜೀವ ಸಂಕೇತಗಳು', emergencyContact: 'ತುರ್ತು ಸಂಪರ್ಕ', preferredHospitals: 'ಆದ್ಯತೆಯ ಆಸ್ಪತ್ರೆಗಳು',
    saveProfile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ', profileSaved: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ!', saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ…',
    privateData: 'ಖಾಸಗಿ — ನಿಮಗೆ ಮಾತ್ರ ಗೋಚರಿಸುತ್ತದೆ',
    profileAutoFills: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ — SOS ಎಚ್ಚರಿಕೆಗಳಲ್ಲಿ ಸ್ವಯಂ ತುಂಬಿಸುತ್ತದೆ',
    completeProfile: 'ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    organDonor: 'ನಾನು ಅಂಗ ದಾನಿ', doctorNotes: 'ವೈದ್ಯರಿಗೆ ವಿಶೇಷ ಟಿಪ್ಪಣಿಗಳು',
    insurance: 'ವಿಮೆ', hasInsurance: 'ನನಗೆ ಆರೋಗ್ಯ ವಿಮೆ ಇದೆ', policyNumber: 'ಪಾಲಿಸಿ ಸಂಖ್ಯೆ',
    profilePicture: 'ಪ್ರೊಫೈಲ್ ಚಿತ್ರ', uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು', email: 'ಇಮೇಲ್', bio: 'ಪರಿಚಯ', saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    appearance: 'ನೋಟ', lightMode: 'ಬೆಳಕು', darkMode: 'ಕತ್ತಲೆ', systemMode: 'ಸಿಸ್ಟಮ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು', privacy: 'ಗೌಪ್ಯತೆ', signOut: 'ಸೈನ್ ಔಟ್',
    deleteAccount: 'ಖಾತೆ ಮತ್ತು ಡೇಟಾ ಅಳಿಸಿ',
    emergency_title: 'ತುರ್ತು?', emergency_subtitle: 'ತಕ್ಷಣ ಸಹಾಯ ಒಂದು ಟ್ಯಾಪ್ ದೂರದಲ್ಲಿದೆ.',
    reportEmergency: 'ತುರ್ತನ್ನು ವರದಿ ಮಾಡಿ', yourName: 'ನಿಮ್ಮ ಹೆಸರು', roomNo: 'ಕೋಣೆ ಸಂಖ್ಯೆ', floor: 'ಮಹಡಿ',
    emergencyType: 'ತುರ್ತು ವಿಧ', describeEmergency: 'ತುರ್ತನ್ನು ವಿವರಿಸಿ', sendAlert: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ',
    alertCreated: 'ಎಚ್ಚರಿಕೆ ರಚಿಸಲಾಗಿದೆ', helpDispatched: 'ಸಹಾಯ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ',
    medicalProfileLoaded: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಸ್ವಯಂ ಲೋಡ್ ಆಗಿದೆ',
    noProfileFound: 'ವೈದ್ಯಕೀಯ ಪ್ರೊಫೈಲ್ ಕಂಡುಬಂದಿಲ್ಲ.', setOneUp: 'ಒಂದು ಸೆಟಪ್ ಮಾಡಿ',
    fasterCare: 'ವೇಗವಾದ ತುರ್ತು ಆರೈಕೆಗಾಗಿ.',
    profileSentToHospital: 'ಈ ಡೇಟಾ ಹೋಟೆಲ್ ಸಿಬ್ಬಂದಿ ಮತ್ತು ಆಸ್ಪತ್ರೆಗೆ ಸ್ವಯಂ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
    hospitalPortal: 'ಆಸ್ಪತ್ರೆ ತುರ್ತು ಪೋರ್ಟಲ್', incomingPatients: 'ಒಳಬರುವ ರೋಗಿಗಳು',
    acknowledgeAlert: 'ಎಚ್ಚರಿಕೆ ಸ್ವೀಕರಿಸಿ', bedReady: 'ಹಾಸಿಗೆ ಸಿದ್ಧ', patientArrived: 'ರೋಗಿ ಬಂದರು',
    assignBed: 'ಹಾಸಿಗೆ ನಿಯೋಜಿಸಿ', assignResponder: 'ಪ್ರತಿಸ್ಪಂದಕ ನಿಯೋಜಿಸಿ',
    noIncomingAlerts: 'ಒಳಬರುವ ರೋಗಿ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ', icdCode: 'ICD-10 ಕೋಡ್', condition_label: 'ಸ್ಥಿತಿ',
    department: 'ವಿಭಾಗ', bloodType: 'ರಕ್ತ ವಿಧ', knownConditions: 'ತಿಳಿದ ಸ್ಥಿತಿಗಳು',
    medications: 'ಔಷಧಗಳು', preferredHospital: 'ಆದ್ಯತೆಯ ಆಸ್ಪತ್ರೆ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ', signIn: 'ಸೈನ್ ಇನ್', signUp: 'ಸೈನ್ ಅಪ್',
    continueWithGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ', or: 'ಅಥವಾ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', submit: 'ಸಲ್ಲಿಸಿ', refresh: 'ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    connected: 'ಸಂಪರ್ಕಿತ', connecting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...', error: 'ದೋಷ', success: 'ಯಶಸ್ಸು',
  },

  mr: {
    dashboard: 'डॅशबोर्ड', askAIDoctor: 'AI डॉक्टरांना विचारा', symptomChecker: 'लक्षण तपासक',
    medicineFinder: 'औषध शोधक', medicineScanner: 'औषध स्कॅनर', medicalReports: 'वैद्यकीय अहवाल',
    healthTracker: 'आरोग्य ट्रॅकर', appointments: 'अपॉइंटमेंट्स', emergency: 'आणीबाणी',
    hospitals: 'रुग्णालये', settings: 'सेटिंग्ज',
    searchPlaceholder: 'लक्षणे, औषधे, आजारांबद्दल विचारा...', onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'नजीकची रुग्णालये', viewAll: 'सर्व पहा', selectLocation: 'स्थान निवडा',
    medicineInfo: 'औषध माहिती', scanMedicine: 'औषध स्कॅन करा',
    scanDescription: 'कोणतेही औषध त्वरित स्कॅन करा आणि तपशील मिळवा',
    aiDiagnosis: 'AI निदान सूचना', healthStats: 'आरोग्य आकडेवारी', heartRate: 'हृदय गती',
    bloodPressure: 'रक्तदाब', sugarLevel: 'शुगर लेव्हल', enterSymptoms: 'खाली आपली लक्षणे प्रविष्ट करा',
    aiSuggestion: 'AI सूचना', possibleViral: 'संभाव्य व्हायरल इन्फेक्शन', condition: 'संभाव्य स्थिती',
    openFull: 'पूर्ण तपासक उघडा', usedFor: 'साठी वापरले जाते', dosage: 'डोस', availability: 'उपलब्धता',
    healthPredictors: 'आरोग्य भविष्यवेत्ता',
    medicalProfile: 'वैद्यकीय प्रोफाइल', myMedicalProfile: 'माझी वैद्यकीय प्रोफाइल',
    personalInfo: 'वैयक्तिक माहिती', fullName: 'पूर्ण नाव', age: 'वय', dateOfBirth: 'जन्म तारीख',
    gender: 'लिंग', bloodGroup: 'रक्त गट', height: 'उंची (सेमी)', weight: 'वजन (किग्रा)',
    medicalConditions: 'वैद्यकीय परिस्थिती', currentMedications: 'सध्याची औषधे', allergies: 'ऍलर्जी',
    vitals: 'जीव संकेत', emergencyContact: 'आणीबाणी संपर्क', preferredHospitals: 'पसंतीची रुग्णालये',
    saveProfile: 'प्रोफाइल जतन करा', profileSaved: 'प्रोफाइल जतन केली!', saving: 'जतन होत आहे…',
    privateData: 'खाजगी — फक्त तुम्हाला दिसते',
    profileAutoFills: 'प्रोफाइल जतन — SOS अलर्टमध्ये आपोआप भरते',
    completeProfile: 'तुमची वैद्यकीय प्रोफाइल पूर्ण करा',
    organDonor: 'मी अवयव दाता आहे', doctorNotes: 'डॉक्टरांसाठी विशेष नोट्स',
    insurance: 'विमा', hasInsurance: 'माझ्याकडे आरोग्य विमा आहे', policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफाइल चित्र', uploadPhoto: 'फोटो अपलोड करा',
    displayName: 'प्रदर्शन नाव', email: 'ईमेल', bio: 'परिचय', saveChanges: 'बदल जतन करा',
    appearance: 'दिसणे', lightMode: 'प्रकाश', darkMode: 'अंधार', systemMode: 'सिस्टम',
    notifications: 'सूचना', privacy: 'गोपनीयता', signOut: 'साइन आउट',
    deleteAccount: 'खाते आणि डेटा हटवा',
    emergency_title: 'आणीबाणी?', emergency_subtitle: 'त्वरित मदत एका टॅपवर आहे.',
    reportEmergency: 'आणीबाणी नोंदवा', yourName: 'तुमचे नाव', roomNo: 'खोली क्रमांक', floor: 'मजला',
    emergencyType: 'आणीबाणीचा प्रकार', describeEmergency: 'आणीबाणीचे वर्णन करा',
    sendAlert: 'आणीबाणी अलर्ट पाठवा', alertCreated: 'अलर्ट तयार झाला', helpDispatched: 'मदत पाठवली जात आहे',
    medicalProfileLoaded: 'वैद्यकीय प्रोफाइल आपोआप लोड झाली',
    noProfileFound: 'वैद्यकीय प्रोफाइल आढळली नाही.', setOneUp: 'एक सेट करा',
    fasterCare: 'जलद आणीबाणी काळजीसाठी.',
    profileSentToHospital: 'हा डेटा हॉटेल कर्मचारी आणि रुग्णालयाला आपोआप पाठवला जाईल.',
    hospitalPortal: 'रुग्णालय आणीबाणी पोर्टल', incomingPatients: 'येणारे रुग्ण',
    acknowledgeAlert: 'अलर्ट स्वीकारा', bedReady: 'बेड तयार', patientArrived: 'रुग्ण आला',
    assignBed: 'बेड नियुक्त करा', assignResponder: 'प्रतिसादकर्ता नियुक्त करा',
    noIncomingAlerts: 'येणारे रुग्ण अलर्ट नाहीत', icdCode: 'ICD-10 कोड', condition_label: 'स्थिती',
    department: 'विभाग', bloodType: 'रक्त प्रकार', knownConditions: 'ज्ञात परिस्थिती',
    medications: 'औषधे', preferredHospital: 'पसंतीचे रुग्णालय',
    welcomeBack: 'पुन्हा स्वागत', signIn: 'साइन इन', signUp: 'साइन अप',
    continueWithGoogle: 'Google सह सुरू ठेवा', or: 'किंवा',
    loading: 'लोड होत आहे...', save: 'जतन करा', cancel: 'रद्द करा', close: 'बंद करा',
    back: 'मागे', next: 'पुढे', submit: 'सबमिट करा', refresh: 'रिफ्रेश करा',
    connected: 'कनेक्ट झाले', connecting: 'कनेक्ट होत आहे...', error: 'त्रुटी', success: 'यश',
  },

  bn: {
    dashboard: 'ড্যাশবোর্ড', askAIDoctor: 'AI ডাক্তারকে জিজ্ঞাসা করুন', symptomChecker: 'উপসর্গ পরীক্ষক',
    medicineFinder: 'ওষুধ খোঁজার যন্ত্র', medicineScanner: 'ওষুধ স্ক্যানার', medicalReports: 'মেডিক্যাল রিপোর্ট',
    healthTracker: 'স্বাস্থ্য ট্র্যাকার', appointments: 'অ্যাপয়েন্টমেন্ট', emergency: 'জরুরী',
    hospitals: 'হাসপাতাল', settings: 'সেটিংস',
    searchPlaceholder: 'উপসর্গ, ওষুধ, রোগ সম্পর্কে জিজ্ঞাসা করুন...', onlineDoctor: 'অনলাইন ডাক্তার',
    nearbyHospitals: 'নিকটস্থ হাসপাতাল', viewAll: 'সব দেখুন', selectLocation: 'স্থান নির্বাচন করুন',
    medicineInfo: 'ওষুধের তথ্য', scanMedicine: 'ওষুধ স্ক্যান করুন',
    scanDescription: 'যেকোনো ওষুধ স্ক্যান করুন এবং বিস্তারিত জানুন',
    aiDiagnosis: 'AI ডায়াগনোসিস পরামর্শ', healthStats: 'স্বাস্থ্য পরিসংখ্যান', heartRate: 'হৃৎস্পন্দন',
    bloodPressure: 'রক্তচাপ', sugarLevel: 'সুগার লেভেল', enterSymptoms: 'নিচে আপনার উপসর্গ লিখুন',
    aiSuggestion: 'AI পরামর্শ', possibleViral: 'সম্ভাব্য ভাইরাল সংক্রমণ', condition: 'সম্ভাব্য অবস্থা',
    openFull: 'পুরো পরীক্ষক খুলুন', usedFor: 'জন্য ব্যবহৃত', dosage: 'ডোজ', availability: 'উপলব্ধতা',
    healthPredictors: 'স্বাস্থ্য ভবিষ্যৎবক্তা',
    medicalProfile: 'মেডিকেল প্রোফাইল', myMedicalProfile: 'আমার মেডিকেল প্রোফাইল',
    personalInfo: 'ব্যক্তিগত তথ্য', fullName: 'পুরো নাম', age: 'বয়স', dateOfBirth: 'জন্ম তারিখ',
    gender: 'লিঙ্গ', bloodGroup: 'রক্তের গ্রুপ', height: 'উচ্চতা (সেমি)', weight: 'ওজন (কেজি)',
    medicalConditions: 'চিকিৎসা অবস্থা', currentMedications: 'বর্তমান ওষুধ', allergies: 'অ্যালার্জি',
    vitals: 'গুরুত্বপূর্ণ লক্ষণ', emergencyContact: 'জরুরী যোগাযোগ', preferredHospitals: 'পছন্দের হাসপাতাল',
    saveProfile: 'প্রোফাইল সংরক্ষণ করুন', profileSaved: 'প্রোফাইল সংরক্ষিত!', saving: 'সংরক্ষণ হচ্ছে…',
    privateData: 'ব্যক্তিগত — শুধুমাত্র আপনাকে দেখায়',
    profileAutoFills: 'প্রোফাইল সংরক্ষিত — SOS সতর্কতায় স্বয়ংক্রিয়ভাবে পূরণ হয়',
    completeProfile: 'আপনার মেডিকেল প্রোফাইল সম্পন্ন করুন',
    organDonor: 'আমি একজন অঙ্গ দাতা', doctorNotes: 'ডাক্তারদের জন্য বিশেষ নোট',
    insurance: 'বীমা', hasInsurance: 'আমার স্বাস্থ্য বীমা আছে', policyNumber: 'পলিসি নম্বর',
    profilePicture: 'প্রোফাইল ছবি', uploadPhoto: 'ছবি আপলোড করুন',
    displayName: 'প্রদর্শনী নাম', email: 'ইমেইল', bio: 'জীবনী', saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    appearance: 'চেহারা', lightMode: 'আলো', darkMode: 'অন্ধকার', systemMode: 'সিস্টেম',
    notifications: 'বিজ্ঞপ্তি', privacy: 'গোপনীয়তা', signOut: 'সাইন আউট',
    deleteAccount: 'অ্যাকাউন্ট এবং ডেটা মুছুন',
    emergency_title: 'জরুরী?', emergency_subtitle: 'তাৎক্ষণিক সাহায্য এক ট্যাপ দূরে।',
    reportEmergency: 'জরুরী রিপোর্ট করুন', yourName: 'আপনার নাম', roomNo: 'ঘর নম্বর', floor: 'তলা',
    emergencyType: 'জরুরী ধরন', describeEmergency: 'জরুরীর বর্ণনা দিন',
    sendAlert: 'জরুরী সতর্কতা পাঠান', alertCreated: 'সতর্কতা তৈরি হয়েছে', helpDispatched: 'সাহায্য পাঠানো হচ্ছে',
    medicalProfileLoaded: 'মেডিকেল প্রোফাইল স্বয়ংক্রিয়ভাবে লোড হয়েছে',
    noProfileFound: 'কোনো মেডিকেল প্রোফাইল পাওয়া যায়নি।', setOneUp: 'একটি সেটআপ করুন',
    fasterCare: 'দ্রুত জরুরী যত্নের জন্য।',
    profileSentToHospital: 'এই ডেটা স্বয়ংক্রিয়ভাবে হোটেল কর্মী এবং হাসপাতালে পাঠানো হবে।',
    hospitalPortal: 'হাসপাতাল জরুরী পোর্টাল', incomingPatients: 'আগত রোগী',
    acknowledgeAlert: 'সতর্কতা স্বীকার করুন', bedReady: 'বেড প্রস্তুত', patientArrived: 'রোগী এসেছে',
    assignBed: 'বেড বরাদ্দ করুন', assignResponder: 'রেসপন্ডার নিযুক্ত করুন',
    noIncomingAlerts: 'কোনো আগত রোগীর সতর্কতা নেই', icdCode: 'ICD-10 কোড', condition_label: 'অবস্থা',
    department: 'বিভাগ', bloodType: 'রক্তের ধরন', knownConditions: 'পরিচিত অবস্থা',
    medications: 'ওষুধ', preferredHospital: 'পছন্দের হাসপাতাল',
    welcomeBack: 'স্বাগত ফিরে', signIn: 'সাইন ইন', signUp: 'সাইন আপ',
    continueWithGoogle: 'Google দিয়ে চালিয়ে যান', or: 'বা',
    loading: 'লোড হচ্ছে...', save: 'সংরক্ষণ করুন', cancel: 'বাতিল করুন', close: 'বন্ধ করুন',
    back: 'পিছনে', next: 'পরবর্তী', submit: 'জমা দিন', refresh: 'রিফ্রেশ করুন',
    connected: 'সংযুক্ত', connecting: 'সংযুক্ত হচ্ছে...', error: 'ত্রুটি', success: 'সাফল্য',
  },

  bho: {
    dashboard: 'डैशबोर्ड', askAIDoctor: 'AI डॉक्टर से पूछीं', symptomChecker: 'लक्षण जाँचे वाला',
    medicineFinder: 'दवाई खोजे वाला', medicineScanner: 'दवाई स्कैनर', medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर', appointments: 'अपॉइंटमेंट', emergency: 'आपातकालीन',
    hospitals: 'अस्पताल', settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षण, दवाई, बेमारी के बारे में पूछीं...', onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'लगे के अस्पताल', viewAll: 'सब देखीं', selectLocation: 'जगह चुनीं',
    medicineInfo: 'दवाई के जानकारी', scanMedicine: 'दवाई स्कैन करीं',
    scanDescription: 'कौनो भी दवाई के तुरंत स्कैन करीं आउर जानकारी पाईं',
    aiDiagnosis: 'AI निदान सलाह', healthStats: 'स्वास्थ्य आँकड़ा', heartRate: 'दिल के धड़कन',
    bloodPressure: 'ब्लड प्रेशर', sugarLevel: 'शुगर लेवल', enterSymptoms: 'नीचे आपन लक्षण लिखीं',
    aiSuggestion: 'AI सलाह', possibleViral: 'वायरल इन्फेक्शन हो सकेला', condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलीं', usedFor: 'खातिर इस्तेमाल होला', dosage: 'खुराक', availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
    medicalProfile: 'मेडिकल प्रोफाइल', myMedicalProfile: 'हमार मेडिकल प्रोफाइल',
    personalInfo: 'निजी जानकारी', fullName: 'पूरा नाम', age: 'उमर', dateOfBirth: 'जनम के तारीख',
    gender: 'लिंग', bloodGroup: 'खून के ग्रुप', height: 'ऊँचाई (सेमी)', weight: 'वजन (किग्रा)',
    medicalConditions: 'चिकित्सा स्थिति', currentMedications: 'अभी के दवाई', allergies: 'एलर्जी',
    vitals: 'जीव संकेत', emergencyContact: 'आपातकालीन संपर्क', preferredHospitals: 'पसंदीदा अस्पताल',
    saveProfile: 'प्रोफाइल सहेजीं', profileSaved: 'प्रोफाइल सहेजाइल!', saving: 'सहेजात बा…',
    privateData: 'निजी — बस आपहीं के देखाई देला',
    profileAutoFills: 'प्रोफाइल सहेजाइल — SOS अलर्ट में आपने भराई',
    completeProfile: 'आपन मेडिकल प्रोफाइल पूरा करीं',
    organDonor: 'हम अंग दाता हईं', doctorNotes: 'डॉक्टर लोगन खातिर विशेष नोट',
    insurance: 'बीमा', hasInsurance: 'हमरे पास स्वास्थ्य बीमा बा', policyNumber: 'पॉलिसी नंबर',
    profilePicture: 'प्रोफाइल फोटो', uploadPhoto: 'फोटो अपलोड करीं',
    displayName: 'प्रदर्शन नाम', email: 'ईमेल', bio: 'परिचय', saveChanges: 'बदलाव सहेजीं',
    appearance: 'दिखावट', lightMode: 'उजियार', darkMode: 'अँधेरा', systemMode: 'सिस्टम',
    notifications: 'सूचना', privacy: 'गोपनीयता', signOut: 'साइन आउट',
    deleteAccount: 'खाता आउर डेटा मेटाईं',
    emergency_title: 'आपातकाल?', emergency_subtitle: 'फटाफट मदद एक टैप दूर बा।',
    reportEmergency: 'आपातकाल जानकारी दीं', yourName: 'आपन नाम', roomNo: 'कमरा नंबर', floor: 'मंजिल',
    emergencyType: 'आपातकाल के प्रकार', describeEmergency: 'आपातकाल के बारे में बताईं',
    sendAlert: 'आपातकाल अलर्ट भेजीं', alertCreated: 'अलर्ट बनाइल गइल', helpDispatched: 'मदद भेजात बा',
    medicalProfileLoaded: 'मेडिकल प्रोफाइल आपने लोड भइल',
    noProfileFound: 'कउनो मेडिकल प्रोफाइल ना मिलल।', setOneUp: 'एक बनाईं',
    fasterCare: 'तेज आपातकालीन देखभाल खातिर।',
    profileSentToHospital: 'ई डेटा होटल स्टाफ आउर अस्पताल के आपने भेजाई।',
    hospitalPortal: 'अस्पताल आपातकाल पोर्टल', incomingPatients: 'आवत रहे वाला मरीज',
    acknowledgeAlert: 'अलर्ट मान लीं', bedReady: 'बेड तैयार', patientArrived: 'मरीज आ गइल',
    assignBed: 'बेड दीं', assignResponder: 'रेस्पॉंडर नियुक्त करीं',
    noIncomingAlerts: 'कउनो आवत मरीज अलर्ट नइखे', icdCode: 'ICD-10 कोड', condition_label: 'स्थिति',
    department: 'विभाग', bloodType: 'खून के प्रकार', knownConditions: 'जानल स्थिति',
    medications: 'दवाई', preferredHospital: 'पसंदीदा अस्पताल',
    welcomeBack: 'फिर से स्वागत', signIn: 'साइन इन', signUp: 'साइन अप',
    continueWithGoogle: 'Google से जारी रखीं', or: 'या',
    loading: 'लोड होत बा...', save: 'सहेजीं', cancel: 'रद्द करीं', close: 'बंद करीं',
    back: 'पाछे', next: 'अगिला', submit: 'सबमिट करीं', refresh: 'रिफ्रेश करीं',
    connected: 'कनेक्टेड', connecting: 'कनेक्ट होत बा...', error: 'गलती', success: 'सफलता',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    window.dispatchEvent(new CustomEvent('language-changed', { detail: lang }));
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Return a no-op fallback instead of throwing — allows use outside provider (e.g. SOS page)
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}
