'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'te' | 'hi' | 'ta' | 'kn' | 'mr' | 'bn' | 'bho';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    askAIDoctor: 'Ask AI Doctor',
    symptomChecker: 'Symptom Checker',
    medicineFinder: 'Medicine Finder',
    medicineScanner: 'Medicine Scanner',
    medicalReports: 'Medical Reports',
    healthTracker: 'Health Tracker',
    appointments: 'Appointments',
    emergency: 'Emergency',
    hospitals: 'Hospitals',
    settings: 'Settings',
    searchPlaceholder: 'Ask about symptoms, medicines, diseases...',
    onlineDoctor: 'Online Doctor',
    nearbyHospitals: 'Nearby Hospitals',
    viewAll: 'View All',
    selectLocation: 'Select Location',
    medicineInfo: 'Medicine Info',
    scanMedicine: 'Scan Medicine',
    scanDescription: 'Scan any medicine to get complete details instantly',
    aiDiagnosis: 'AI Diagnosis Suggestion',
    healthStats: 'Health Stats',
    heartRate: 'Heart Rate',
    bloodPressure: 'Blood Pressure',
    sugarLevel: 'Sugar Level',
    enterSymptoms: 'Enter your symptoms below',
    aiSuggestion: 'AI Suggestion',
    possibleViral: 'Possible Viral Infection',
    condition: 'Possible Condition',
    openFull: 'Open Full Checker',
    usedFor: 'Used for',
    dosage: 'Dosage',
    availability: 'Availability',
    healthPredictors: 'Health Predictors',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    askAIDoctor: 'AI డాక్టర్‌ని అడగండి',
    symptomChecker: 'లక్షణాల తనిఖీ',
    medicineFinder: 'మందుల అన్వేషణ',
    medicineScanner: 'మందుల స్కానర్',
    medicalReports: 'వైద్య నివేదికలు',
    healthTracker: 'ఆరోగ్య ట్రాకర్',
    appointments: 'అపాయింట్‌మెంట్‌లు',
    emergency: 'అత్యవసర',
    hospitals: 'ఆసుపత్రులు',
    settings: 'సెట్టింగ్‌లు',
    searchPlaceholder: 'లక్షణాలు, మందులు, వ్యాధుల గురించి అడగండి...',
    onlineDoctor: 'ఆన్‌లైన్ డాక్టర్',
    nearbyHospitals: 'సమీప ఆసుపత్రులు',
    viewAll: 'అన్నీ చూడు',
    selectLocation: 'స్థానాన్ని ఎంచుకోండి',
    medicineInfo: 'మందుల సమాచారం',
    scanMedicine: 'మెడిసిన్ స్కాన్ చేయండి',
    scanDescription: 'ఏదైనా మందుని తక్షణమే స్కాన్ చేసి వివరాలు పొందండి',
    aiDiagnosis: 'AI రోగనిర్ధారణ సూచన',
    healthStats: 'ఆరోగ్య గణాంకాలు',
    heartRate: 'గుండె వేగం',
    bloodPressure: 'రక్తపోటు',
    sugarLevel: 'షుగర్ లెవల్',
    enterSymptoms: 'మీ లక్షణాలను క్రింద నమోదు చేయండి',
    aiSuggestion: 'AI సూచన',
    possibleViral: 'వైరల్ ఇన్ఫెక్షన్ కావచ్చు',
    condition: 'సాధ్యమైన పరిస్థితి',
    openFull: 'పూర్తి తనిఖీని తెరవండి',
    usedFor: 'కోసం ఉపయోగించబడుతుంది',
    dosage: 'మోతాదు',
    availability: 'అందుబాటులో ఉంది',
    healthPredictors: 'ఆరోగ్య అంచనాలు',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    askAIDoctor: 'AI डॉक्टर से पूछें',
    symptomChecker: 'लक्षण जाँचक',
    medicineFinder: 'दवा खोजक',
    medicineScanner: 'दवा स्कैनर',
    medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर',
    appointments: 'अपॉइंटमेंट',
    emergency: 'आपातकालीन',
    hospitals: 'अस्पताल',
    settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षणों, दवाओं, रोगों के बारे में पूछें...',
    onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'पास के अस्पताल',
    viewAll: 'सभी देखें',
    selectLocation: 'स्थान चुनें',
    medicineInfo: 'दवा की जानकारी',
    scanMedicine: 'दवा स्कैन करें',
    scanDescription: 'किसी भी दवा को तुरंत स्कैन करें और विवरण प्राप्त करें',
    aiDiagnosis: 'AI निदान सुझाव',
    healthStats: 'स्वास्थ्य आँकड़े',
    heartRate: 'हृदय गति',
    bloodPressure: 'रक्तचाप',
    sugarLevel: 'शुगर लेवल',
    enterSymptoms: 'नीचे अपने लक्षण दर्ज करें',
    aiSuggestion: 'AI सुझाव',
    possibleViral: 'संभावित वायरल संक्रमण',
    condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलें',
    usedFor: 'के लिए उपयोग किया जाता है',
    dosage: 'खुराक',
    availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    askAIDoctor: 'AI மருத்துவரிடம் கேளுங்கள்',
    symptomChecker: 'அறிகுறி சரிபார்ப்பு',
    medicineFinder: 'மருந்து தேடல்',
    medicineScanner: 'மருந்து ஸ்கேனர்',
    medicalReports: 'மருத்துவ அறிக்கைகள்',
    healthTracker: 'சுகாதார டிராக்கர்',
    appointments: 'நியமனங்கள்',
    emergency: 'அவசரம்',
    hospitals: 'மருத்துவமனைகள்',
    settings: 'அமைப்புகள்',
    searchPlaceholder: 'அறிகுறிகள், மருந்துகள், நோய்கள் பற்றி கேளுங்கள்...',
    onlineDoctor: 'ஆன்லைன் மருத்துவர்',
    nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    viewAll: 'அனைத்தையும் பார்',
    selectLocation: 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
    medicineInfo: 'மருந்து தகவல்',
    scanMedicine: 'மருந்தை ஸ்கேன் செய்யுங்கள்',
    scanDescription: 'எந்த மருந்தையும் உடனடியாக ஸ்கேன் செய்து விவரங்களைப் பெறுங்கள்',
    aiDiagnosis: 'AI நோயறிதல் பரிந்துரை',
    healthStats: 'சுகாதார புள்ளிவிவரங்கள்',
    heartRate: 'இதய துடிப்பு',
    bloodPressure: 'இரத்த அழுத்தம்',
    sugarLevel: 'சர்க்கரை அளவு',
    enterSymptoms: 'உங்கள் அறிகுறிகளை கீழே உள்ளிடவும்',
    aiSuggestion: 'AI பரிந்துரை',
    possibleViral: 'வைரஸ் தொற்று இருக்கலாம்',
    condition: 'சாத்தியமான நிலை',
    openFull: 'முழு சரிபார்ப்பைத் திற',
    usedFor: 'பயன்படுத்தப்படுகிறது',
    dosage: 'அளவு',
    availability: 'கிடைக்கும் தன்மை',
    healthPredictors: 'சுகாதார முன்கணிப்பாளர்கள்',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    askAIDoctor: 'AI ವೈದ್ಯರನ್ನು ಕೇಳಿ',
    symptomChecker: 'ಲಕ್ಷಣಗಳ ತಪಾಸಣೆ',
    medicineFinder: 'ಔಷಧ ಶೋಧಕ',
    medicineScanner: 'ಔಷಧ ಸ್ಕ್ಯಾನರ್',
    medicalReports: 'ವೈದ್ಯಕೀಯ ವರದಿಗಳು',
    healthTracker: 'ಆರೋಗ್ಯ ಟ್ರ್ಯಾಕರ್',
    appointments: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
    emergency: 'ತುರ್ತು',
    hospitals: 'ಆಸ್ಪತ್ರೆಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    searchPlaceholder: 'ಲಕ್ಷಣಗಳು, ಔಷಧಗಳು, ಕಾಯಿಲೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    onlineDoctor: 'ಆನ್‌ಲೈನ್ ವೈದ್ಯರು',
    nearbyHospitals: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    selectLocation: 'ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    medicineInfo: 'ಔಷಧ ಮಾಹಿತಿ',
    scanMedicine: 'ಔಷಧ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanDescription: 'ತಕ್ಷಣದ ವಿವರಗಳನ್ನು ಪಡೆಯಲು ಯಾವುದೇ ಔಷಧವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    aiDiagnosis: 'AI ರೋಗನಿರ್ಣಯ ಸಲಹೆ',
    healthStats: 'ಆರೋಗ್ಯ ಅಂಕಿಅಂಶಗಳು',
    heartRate: 'ಹೃದಯ ಬಡಿತ',
    bloodPressure: 'ರಕ್ತದೊತ್ತಡ',
    sugarLevel: 'ಸಕ್ಕರೆ ಮಟ್ಟ',
    enterSymptoms: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಕೆಳಗೆ ನಮೂದಿಸಿ',
    aiSuggestion: 'AI ಸಲಹೆ',
    possibleViral: 'ವೈರಲ್ ಸೋಂಕು ಇರಬಹುದು',
    condition: 'ಸಂಭವನೀಯ ಸ್ಥಿತಿ',
    openFull: 'ಪೂರ್ಣ ತಪಾಸಣೆ ತೆರೆಯಿರಿ',
    usedFor: 'ಬಳಸಲಾಗುತ್ತದೆ',
    dosage: 'ಡೋಸೇಜ್',
    availability: 'ಲಭ್ಯತೆ',
    healthPredictors: 'ಆರೋಗ್ಯ ಮುನ್ಸೂಚಕಗಳು',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    askAIDoctor: 'AI डॉक्टरांना विचारा',
    symptomChecker: 'लक्षण तपासक',
    medicineFinder: 'औषध शोधक',
    medicineScanner: 'औषध स्कॅनर',
    medicalReports: 'वैद्यकीय अहवाल',
    healthTracker: 'आरोग्य ट्रॅकर',
    appointments: 'अपॉइंटमेंट्स',
    emergency: 'आणीबाणी',
    hospitals: 'रुग्णालये',
    settings: 'सेटिंग्ज',
    searchPlaceholder: 'लक्षणे, औषधे, आजारांबद्दल विचारा...',
    onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'नजीकची रुग्णालये',
    viewAll: 'सर्व पहा',
    selectLocation: 'स्थान निवडा',
    medicineInfo: 'औषध माहिती',
    scanMedicine: 'औषध स्कॅन करा',
    scanDescription: 'कोणतेही औषध त्वरित स्कॅन करा आणि तपशील मिळवा',
    aiDiagnosis: 'AI निदान सूचना',
    healthStats: 'आरोग्य आकडेवारी',
    heartRate: 'हृदय गती',
    bloodPressure: 'रक्तदाब',
    sugarLevel: 'शुगर लेव्हल',
    enterSymptoms: 'खाली आपली लक्षणे प्रविष्ट करा',
    aiSuggestion: 'AI सूचना',
    possibleViral: 'संभाव्य व्हायरल इन्फेक्शन',
    condition: 'संभाव्य स्थिती',
    openFull: 'पूर्ण तपासक उघडा',
    usedFor: 'साठी वापरले जाते',
    dosage: 'डोस',
    availability: 'उपलब्धता',
    healthPredictors: 'आरोग्य भविष्यवेत्ता',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    askAIDoctor: 'AI ডাক্তারকে জিজ্ঞাসা করুন',
    symptomChecker: 'উপসর্গ পরীক্ষক',
    medicineFinder: 'ওষুধ খোঁজার যন্ত্র',
    medicineScanner: 'ওষুধ স্ক্যানার',
    medicalReports: 'মেডিক্যাল রিপোর্ট',
    healthTracker: 'স্বাস্থ্য ট্র্যাকার',
    appointments: 'অ্যাপয়েন্টমেন্ট',
    emergency: 'জরুরী',
    hospitals: 'হাসপাতাল',
    settings: 'সেটিংস',
    searchPlaceholder: 'উপসর্গ, ওষুধ, রোগ সম্পর্কে জিজ্ঞাসা করুন...',
    onlineDoctor: 'অনলাইন ডাক্তার',
    nearbyHospitals: 'নিকটস্থ হাসপাতাল',
    viewAll: 'সব দেখুন',
    selectLocation: 'স্থান নির্বাচন করুন',
    medicineInfo: 'ওষুধের তথ্য',
    scanMedicine: 'ওষুধ স্ক্যান করুন',
    scanDescription: 'যেকোনো ওষুধ স্ক্যান করুন এবং বিস্তারিত জানুন',
    aiDiagnosis: 'AI ডায়াগনোসিস পরামর্শ',
    healthStats: 'স্বাস্থ্য পরিসংখ্যান',
    heartRate: 'হৃৎস্পন্দন',
    bloodPressure: 'রক্তচাপ',
    sugarLevel: 'সুগার লেভেল',
    enterSymptoms: 'নিচে আপনার উপসর্গ লিখুন',
    aiSuggestion: 'AI পরামর্শ',
    possibleViral: 'সম্ভাব্য ভাইরাল সংক্রমণ',
    condition: 'সম্ভাব্য অবস্থা',
    openFull: 'পুরো পরীক্ষক খুলুন',
    usedFor: 'জন্য ব্যবহৃত',
    dosage: 'ডোজ',
    availability: 'উপলব্ধতা',
    healthPredictors: 'স্বাস্থ্য ভবিষ্যৎবক্তা',
  },
  bho: {
    dashboard: 'डैशबोर्ड',
    askAIDoctor: 'AI डॉक्टर से पूछीं',
    symptomChecker: 'लक्षण जाँचे वाला',
    medicineFinder: 'दवाई खोजे वाला',
    medicineScanner: 'दवाई स्कैनर',
    medicalReports: 'मेडिकल रिपोर्ट',
    healthTracker: 'स्वास्थ्य ट्रैकर',
    appointments: 'अपॉइंटमेंट',
    emergency: 'आपातकालीन',
    hospitals: 'अस्पताल',
    settings: 'सेटिंग्स',
    searchPlaceholder: 'लक्षण, दवाई, बेमारी के बारे में पूछीं...',
    onlineDoctor: 'ऑनलाइन डॉक्टर',
    nearbyHospitals: 'लगे के अस्पताल',
    viewAll: 'सब देखीं',
    selectLocation: 'जगह चुनीं',
    medicineInfo: 'दवाई के जानकारी',
    scanMedicine: 'दवाई स्कैन करीं',
    scanDescription: 'कौనో भी दवाई के तुरंत स्कैन करीं आउर जानकारी पाईं',
    aiDiagnosis: 'AI निदान सलाह',
    healthStats: 'स्वास्थ्य आँकड़ा',
    heartRate: 'दिल के धड़कन',
    bloodPressure: 'ब्लड प्रेशर',
    sugarLevel: 'शुगर लेवल',
    enterSymptoms: 'नीचे आपन लक्षण लिखीं',
    aiSuggestion: 'AI सलाह',
    possibleViral: 'वायरल इन्फेक्शन हो सकेला',
    condition: 'संभावित स्थिति',
    openFull: 'पूरा चेकअप खोलीं',
    usedFor: 'खातिर इस्तेमाल होला',
    dosage: 'खुराक',
    availability: 'उपलब्धता',
    healthPredictors: 'स्वास्थ्य भविष्यवक्ता',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    // Dispatch custom event for vanilla components or non-react parts if needed
    window.dispatchEvent(new CustomEvent('language-changed', { detail: lang }));
  };

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
